name: Validate JSON

on:
  push:
    paths:
    - '**.json'

jobs:
  # This workflow contains a single job called "build"
  validate-bees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./bees.schema.json
          INPUT_JSONS: ./bees.json
