name: Validate JSON

on:
  push:
    paths:
    - '**.json'
    - '.github/workflows/validate-json.yml'

jobs:
  validate-bees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON against the schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./bees.schema.json
          INPUT_JSONS: ./bees.json

  validate-flowers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON against the schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./flowers.schema.json
          INPUT_JSONS: ./flowers.json

  validate-nests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON against the schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./nests.schema.json
          INPUT_JSONS: ./nests.json

  # Adapted from
  # https://docs.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
        env:
          CI: true
